[[plugins]]

  package = "netlify-plugin-flutter"

   [plugins.inputs]
    channel = "stable"

[build]
   command = "dart run build_runner build --delete-conflicting-outputs && flutter build web --release --dart-define WORKER_URL=${WORKER_URL}"
   publish = "build/web"